services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=challenger'
      - 'MYSQL_ROOT_PASSWORD=root'
    ports:
      - '3306:3306'

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
